language: shell

env:
  - TEST="sat"
script:
  - echo "Hello World."

branches:
  only:
    - master

jenkins:
  pipeline_jenkinsfile: test/Jenkinsfile
  collect:
    collect:
      artifacts: build/libs/*.jar
      junit: build/test-results/*.xml
